############################# BEPP DOCKER-COMPOSE ############################# 
# 
# @required    docker >= 27
# @description File for build and run project with Docker.
#              use cli 'docker compose -f docker-compose.yml up --build -d'
# 
###############################################################################

services:          
  
  bepp_api:
    container_name: bepp_api
    build: .
    ports:
      - "13121:13129/tcp"
    restart: always

############################# BEPP DOCKER-COMPOSE #############################
