###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  - id: "bepp"
    name: "Bepp"
    type: "library"
    subtypes:
      - Chromiun
      - Chrome
      - Firefox
      - Safari
      - Edge
      - Brave
      - Opera
      - OperaGX
      - Yandex
    version: "1.2.3"
    description: "{{package.description}}"
    homepage: "{{package.homepage}}"
    docs: "{{package.homepage}}/guide/getting-started"
    license: "https://raw.githubusercontent.com/pigeonposse/bepp/main/LICENSE"
    logo: "https://raw.githubusercontent.com/pigeonposse/bepp/main/docs/public/logo.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/bepp/main/docs/public/banner.png"
    status: "active"

###############################################################################
