# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: 'BEPP - A Cross-Browser Extension Builder'
description: 'Package your extension for multiple browsers quickly and easily (Including Safari)'
author: 'pigeonposse'
inputs:
  file:
    required: false
    description: 'Path for config file.'
runs:
  using: "composite"
  steps:
    - name: ⬇️🥡 Install pnpm
      uses: pnpm/action-setup@v4
    - name: ⬇️🟢 Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - name: ⬇️📦 Install dependencies
      run: pnpm install --no-frozen-lockfile
      shell: bash

    - name: 🧩📦 Build bepp core
      run: pnpm --filter core build-ci
      shell: bash
    - name: 🧩📦 Execute bepp
      run: node packages/core/build/cjs/index.cjs build --verbose -c '${{ inputs.file }}'
      shell: bash

branding:
  icon: 'package'
  color: 'purple'
