############################# BEPP DOCKER-COMPOSE ############################# 
# 
# @required    docker >= 27
# @description File for build and run project with Docker.
#              use cli 'docker compose -f docker-compose.yml up --build -d'
# 
###############################################################################

services:          

  osx:
    container_name: docker-osx
    image: sickcodes/docker-osx:big-sur
    platform: linux/amd64 
    environment:
      - DISPLAY=${DISPLAY:-:0.0}
    #   - EXTRA="-display none -vnc 0.0.0.0:99,password=on"
    #   - USERNAME=test
    #   - PASSWORD=test
    #   - "OSX_COMMANDS=/bin/bash -c \"echo Hola desde macos\""
    ports:
      - 54922:10022
      - 5499:5999 
    # stdin_open: true
    # tty: true
    privileged: true
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix

############################# BEPP DOCKER-COMPOSE #############################
