############################# BEPP DOCKER-COMPOSE ############################# 
# 
# @required    docker >= 27
# @description File for build and run project with Docker.
#              use cli 'docker compose -f docker-compose.yml up --build -d'
# 
###############################################################################

services:          

  macos:
    image: dockurr/macos
    container_name: bepp_app_macos_test2
    environment:
      VERSION: "ventura"
      DISK_SIZE: "40G"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
    # devices:
    #   - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8026:8006
      - 5902:5900/tcp
      - 5902:5900/udp
    stop_grace_period: 2m

############################# BEPP DOCKER-COMPOSE #############################
