######################### BEPP DOCKER-COMPOSE ########################
#
# BUILD REPO IN DOCKER WITH DOCKER COMPOSE 
# 
# @description File for build and run project with Docker.
#              you can use npm script 'docker-compose' for run or
#              use cli 'docker-compose -f docker-compose.yml up --build -d'
###############################################################################

version: "3.8"

###############################################################################
# SERVICES
###############################################################################

services:          

  #############################################################################
  # RUN DOCKER IMAGE WITH DOCKERFILE
  #############################################################################
  
  bepp:

    container_name: ${BEPP_CONTAINER_NAME:-bepp}
    build: .
    ports:
      - "13138:13128/tcp"
      - "13139:13129/tcp"
    restart: always

######################### BEPP DOCKER-COMPOSE ########################
