###############################################################################
# RELEASE APPS
# @observations: Only compatible commands must be entered for all platforms. 
#                For example: avoid $@, since windows does not accept it
###############################################################################
name: 🚀🖥️ Release APPs
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Set number for release version'
        type: string
        required: true
      platform:
        description: 'Specify platform to target (optional). If not set, all platforms will be processed.'
        type: string
        required: false

env:
  GITHUB_TOKEN: ${{ github.token }}
  APP_PATH: packages/app
  BUNDLE_LINUX_ARM64_PATH: packages/app/src-tauri/target/aarch64-unknown-linux-gnu/release/bundle

###############################################################################
# JOBS
###############################################################################

jobs:
  release_apps:
    permissions:
      contents: write
      deployments: write
    strategy:
      fail-fast: false
      matrix:
        # @see https://github.com/actions/runner-images
        settings:
          - platform: 'macos-14' # this is arm64
            args: '--target universal-apple-darwin' # build x64, arm64 and universal
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    timeout-minutes: 25
    runs-on: ${{ matrix.settings.platform }}
    env:
      UPDATED_VERSION: ${{ github.event.inputs.version }}
      TARGET_PLATFORM: ${{ github.event.inputs.platform }}
    steps:

      #########################################################################
      # SETUP
      #########################################################################

      - name: ⬇️🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: ⬇️🛎 Checkout
        uses: actions/checkout@v4
      - name: ⬇️🥡 Install pnpm
        uses: pnpm/action-setup@v4
      - name: ⬇️🟢 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: ⬇️🦀 Rust setup (macos only)
        if: runner.os == 'macOS'
        uses: dtolnay/rust-toolchain@stable
        with:
          # Note that compiling an universal macOS application requires both `aarch64-apple-darwin` and `x86_64-apple-darwin` targets to be installed.
          targets: 'aarch64-apple-darwin,x86_64-apple-darwin'
          toolchain: stable
      - name: ⬇️🦀 Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: ⬇️🐳 Set up QEMU (linux arm64)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
      - name: ⬇️🐳 Set up Docker Buildx (linux arm64)
        if: runner.os == 'Linux'
        uses: docker/setup-buildx-action@v1

      #########################################################################
      # PLATFORM CHECK
      #########################################################################

      - name: 📜 Check Target Platform
        if: runner.os != 'Windows'
        run: |
          if [ "${{ env.TARGET_PLATFORM }}" != "" ] && [ "${{ matrix.settings.platform }}" != "${{ env.TARGET_PLATFORM }}" ]; then
            echo "##[error] Platform ${matrix.settings.platform} does not match the target platform ${TARGET_PLATFORM}. Skipping steps."
            exit 1
          fi
        shell: bash
      - name: 📜 Check Target Platform (Windows)
        if: runner.os == 'Windows'
        id: check_platform_windows
        run: |
          if ($env:TARGET_PLATFORM -ne "" -and $env:TARGET_PLATFORM -ne $env:PLATFORM) {
            Write-Host "Platform $($env:PLATFORM) does not match the target platform $($env:TARGET_PLATFORM). Skipping steps."
            exit 1
          } 
        shell: pwsh

      #########################################################################
      # INSTALL AND INIT
      #########################################################################

      - name: ⬇️🦀 install dependencies (ubuntu only)
        if: matrix.settings.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: ⬇️📦 Install dependencies
        run: |
          pnpm install --no-frozen-lockfile

      - name: 📦📄 Get package.json name
        id: pkg
        run: |
          echo "name=$(jq -r '.extra.productName' ./package.json)" >> $GITHUB_OUTPUT
          echo "description=$(jq -r '.description' ./package.json)" >> $GITHUB_OUTPUT
          echo "homepage=$(jq -r '.homepage' ./package.json)" >> $GITHUB_OUTPUT
          echo "docs=$(jq -r '.extra.docsUrl' ./package.json)" >> $GITHUB_OUTPUT
          echo "repo=$(jq -r '.repository.url' ./package.json)" >> $GITHUB_OUTPUT
          {
            echo 'release_body<<EOF'
            pnpm --silent get-release-body
            echo EOF
          } >> "$GITHUB_OUTPUT"


      #########################################################################
      # BUILD REQUERIMENTS FOR APP
      #########################################################################
   
      - name: 🏗 Build
        run: pnpm build:app # Is necessary set manually for windows 

      # BUILD linux arm64
      #########################################################################

      - name: 🖥️ Build app (linux arm64)
        if: runner.os == 'Linux'
        run: pnpm app build:linux-arm64
      - name: 🖥️ Release app (linux arm64)
        if: runner.os == 'Linux'
        uses: ncipollo/release-action@v1
        with: 
          tag: "${{ env.UPDATED_VERSION }}"
          draft: false
          prerelease: false
          allowUpdates: true
          artifacts: "${{ env.BUNDLE_LINUX_ARM64_PATH }}/appimage/*.AppImage,${{ env.BUNDLE_LINUX_ARM64_PATH }}/deb/*.deb,${{ env.BUNDLE_LINUX_ARM64_PATH }}/rpm/*.rpm"
          omitBodyDuringUpdate: true


      #########################################################################
      # APP - BUILD & RELEASE DESKTOP APP
      #
      # @see https://github.com/tauri-apps/tauri-action?tab=readme-ov-file#inputs
      # @see https://github.com/tauri-apps/tauri-action?tab=readme-ov-file#build-options
      #########################################################################

      - name: 🖥️ Build app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: ${{ env.APP_PATH }}
          tagName: "${{ env.UPDATED_VERSION }}" 
          releaseName: '${{ steps.pkg.outputs.name }} v${{ env.UPDATED_VERSION }}'
          releaseBody: |
            ${{steps.pkg.outputs.release_body}}
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
          updaterJsonKeepUniversal: true 
          includeRelease: true
          tauriScript: pnpm exec tauri # This is because the tauri script has $@ and Windows does not support it.
          args: ${{ matrix.settings.args }}

      # BUILD macos arm64/x64
      #########################################################################
      - name: 🖥️ Build app (macos x64)
        if: runner.os == 'macOS'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: ${{ env.APP_PATH }}
          tagName: "${{ env.UPDATED_VERSION }}"
          releaseName: '${{ steps.pkg.outputs.name }} v${{ env.UPDATED_VERSION }}'
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
          updaterJsonKeepUniversal: true 
          includeRelease: true
          tauriScript: pnpm exec tauri 
          args: '--target x86_64-apple-darwin'

      - name: 🖥️ Build app (macos arm64)
        if: runner.os == 'macOS'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          projectPath: ${{ env.APP_PATH }}
          tagName: "${{ env.UPDATED_VERSION }}"
          releaseName: '${{ steps.pkg.outputs.name }} v${{ env.UPDATED_VERSION }}'
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
          updaterJsonKeepUniversal: true 
          includeRelease: true
          tauriScript: pnpm exec tauri 
          args: '--target aarch64-apple-darwin'


############################################################################### 
